Repository vaibhavpathak999/Algorithms, pull requests merged in 2021-10, with the labels that each got.

#42 Added the BST_To_MinHeap.cpp file
  Binary_Search_Tree/BST_To_MinHeap.cpp
Labels: Hacktoberfest

#45 ArrayStack.cpp
  Stack_Queue/ArrayStack.cpp
Labels: Hacktoberfest

#47 Added Sorting Algos and Game
  Game/VideoGame.cpp
  Game/readme.md
  Sorting Algos/Circle_Sort.cpp
  Sorting Algos/Counting_Sort.cpp
  Sorting Algos/Quick Sort/Quick Sort.cpp
  Sorting Algos/Quick Sort/Quick_Sort.cpp
Labels: good first issue, Hacktoberfest

#48 BST programs
  Binary_Search_Tree/LCA.cpp
  Binary_Search_Tree/ValidateBST.cpp
Labels: Hacktoberfest

#49 Create mergeTwoSortedLists.cpp
  LinkedList/mergeTwoSortedLists.cpp
Labels: Hacktoberfest

#51 Create cycleDetection.cpp
  LinkedList/cycleDetection.cpp
Labels: Hacktoberfest

#52 Create nodeCycleBegins.cpp
  LinkedList/nodeCycleBegins.cpp
Labels: Hacktoberfest

#50 Maximum Profit in Job Scheduling
  Dynamic_Programming/Max_profit.cpp
Labels: question, Hacktoberfest

#58 Added Dijkstra's Algorithm
  Graphs/Dijkstras_algorithm.cpp
Labels: Hacktoberfest

#62 Added Connectivity check
  Graphs/check_connectivity.cpp
Labels: Hacktoberfest
